import type { Metadata } from "next";
import { Monomaniac_One } from "next/font/google";
import "./globals.css";

const monomaniac = Monomaniac_One({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ monomaniac.className }>
        { children }
        <footer className="w-full h-[10vh] bg-slate-400 rounded-t-xl">
        </footer>
      </body>
    </html>
  );
}
